language: go

go:
- 1.15.x

script:
- go test ./... -v
- go build -o sshaws *.go
- GOOS=darwin GOARCH=amd64 go build -o sshaws.mac *.go


before_deploy:
  - git config --local user.name "Travis Build"
  - git config --local user.email "builder@travis-ci.com"
  - export TRAVIS_TAG=$(bash travisci/show_version.sh)
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "jeGxw1QVlrS8gf3mYDB2KHcafSjNz7P+G2qAc1k90Q603fqZySZhYGaL76P06iOwpbhddm4tKa1B4DActyy65ppjPkMnW/A0WAJqS32NJPGIlde5sp44DZ9vqc0tPmOl3615VI49c1P4m3wlj4d0l5vWSgHjRYjpernj7DntgC5cPUKx3l9+Xs+TIsrczU0LV1MDmCQ0GBZ04NY0G9Lo1RYBgUDf3Scln4YcJ6JLhsRyJWe6PYFCgMxku4T8VWzDmR8gqi92T+YwGcKZQ/mEoXVQvWh5/ocogut0q6UjWntkJz16E7/sxFVTT0f72k4TmXOwkC9hMOttftSgS+aO1q7BlDCZ0PgIp7pcIhKCnSuVJD3BbnuGyW47Hk9xCwDJt1x740j49QuQsEXXLqUA0ORQcvbAmxxP0N3yWqubtP3jSFSRKmQC2MSHK8ogY0JVieb8X4VdI/J6KdCDiiwByQi0I9vOWZ5N2+UnAEnhlZIsEKn44KDg2VMDgzLlGQ8DbMjY7xmnfprWt05N9f4EayWEs6g583Ug0ObQpUF/oeyKDvXuCdsTPXJdYEMW3EiR9d8eJn4XSx8GFYtxJHq6yJrC0Ec2SIs58ztn8LvrlOVxKyL9Vg1+xaADvKz2tgSphcqaBoSM3OGsRX9iHwWP8oOgxWr4lJccYnUI6xbrdmE="
  file:
  - sshaws
  - sshaws.mac
  skip_cleanup: true
  on:
    branch: master
