language: go
before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_xxxxxxxxxxxx_key
    -iv $encrypted_xxxxxxxxxxxx_iv
    -in travisci/github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key


script:
  - go get .
  - go build -o sshaws *.go

deploy:
    provider: releases
    file:
        - sshaws
    skip_cleanup: true
    on:
        repo: uritau/sshaws
        tags: true