language: go
before_deploy:
      - git config --local user.name "YOUR GIT USER NAME"
      - git config --local user.email "YOUR GIT USER EMAIL"
script:
- go get .
- go build -o sshaws *.go
deploy:
  provider: releases
  api_key:
    secure: GctxAJx1Go1WMBwAVrHLr4uS0aG/lFCDUa1Fl461iW8VdvMGni2FeXgUXqFudHtyKUmkaZvw3H6cug6Yy8k2SPKEkxEitb+Q/rA4CgZ9wo+iNwBj+k2bDn+ucwl05GHXCduwWZbg7wKyEqP8Lz1VHkHhYR60dinct7YPKif2iseBYOz4o7P9+BcqpK0mDKHSgPIzgZqjakF+aiuve1ToC8IdF1B2y7XHWytv+7xpD39Q5MffL0N8pUm4tf9sWQjGRrAjwCk2QykRfh0FStvKj0AO2O1usFKA3oHTrW2pFXgQgZbkLJwRdLd5HzmV2EsI1LrUUCoaUuCwt1SV+XvSauyiJLx7Tt7VbnX2ifXa0kSB/MjxdNh4rpxAVfqOQqaRoJGif+ASi9Fzp08gDcESPQe19M3xwL5eyAJh2PIUdpjhSY1yR2KcNCLpZtaiEbtRspSX61Z+lhLS9yhnPoZgeT5KWcuKsBo2fQQkzVED3nWWFLG2T7m8SWMosKmI7uVTSIn2LwMvlWTgtYb0plnivQqVKxc+mYPOjBueSP5LG4v31lWIP0i5zkkeX+VLvf6yg+4lDxKjHHlTTwNDenAbq3s5MQ4d4fGrYKDwax9MliFBC4cYtYoKt/wLnL2GhXVRpspXBLnu3iRqhc5zfq1t8261FxSfTrqON7CMwRqRuHM=
  file:
  - sshaws
  skip_cleanup: true
  on:
    repo: uritau/sshaws
    tags: true
